apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-demo
spec:
  selector:
    matchLabels:
      run: jenkins-demo
  replicas: 1
  template:
    metadata:
      labels:
        run: jenkins-demo
    spec:
      containers:
      - name: jenkins-demo
        image: 973141472776.dkr.ecr.ap-south-1.amazonaws.com/jenkins-demo3:latest
        ports:
        - containerPort: 9080
